//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankcustomerinfo
    {
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string sex { get; set; }
        public string emailadress { get; set; }
        public int account_number { get; set; }
        public Nullable<int> accountbalance { get; set; }
    }
}
